import { NextRequest, NextResponse } from "next/server"
import { createAdminClient } from "@/lib/supabase/admin"
import { ForgotPasswordSchema } from "@/lib/validation/schemas"
import { sendPasswordReset } from "@/lib/email/resend"
import { evaluateEmailLimit } from "@/lib/auth/email-rate-limit"

// Recovery links generated by Supabase expire after 1 hour by default.
const RESET_LINK_EXPIRY_MINUTES = 60

// Always returned — never reveals whether the email exists, nor whether it is
// currently rate-limited/blocked. Throttling silently suppresses the send.
const GENERIC_OK = {
  ok: true,
  message: "If that email has an account, you'll receive a reset link shortly.",
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  let body: unknown
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 })
  }

  const parsed = ForgotPasswordSchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.issues[0]?.message ?? "Invalid input" },
      { status: 422 },
    )
  }

  const { email } = parsed.data
  const admin = createAdminClient()

  // ── Banned? (shared table — covers verification-abuse bans too) ────────────
  const { data: banned } = await admin
    .from("banned_emails")
    .select("email")
    .eq("email", email)
    .maybeSingle()

  if (banned) {
    // Silently blocked — no send, no disclosure.
    return NextResponse.json(GENERIC_OK, { status: 200 })
  }

  // ── Rate limit: 3/hour, 20-min block, ban after 2 blocks ──────────────────
  // Tracked for every email (existent or not) so the limiter can't be used to
  // probe which addresses have accounts.
  const { data: attempts } = await admin
    .from("password_reset_attempts")
    .select("attempt_count, block_count, blocked_until, window_start")
    .eq("email", email)
    .maybeSingle<{
      attempt_count: number
      block_count: number
      blocked_until: string | null
      window_start: string
    }>()

  const decision = evaluateEmailLimit({
    attemptCount: attempts?.attempt_count ?? 0,
    blockCount: attempts?.block_count ?? 0,
    blockedUntil: attempts?.blocked_until ?? null,
    windowStart: attempts?.window_start ?? new Date().toISOString(),
  })

  if (decision.action === "ban") {
    await admin
      .from("banned_emails")
      .insert({ email, reason: "too_many_password_reset_requests" })
    return NextResponse.json(GENERIC_OK, { status: 200 })
  }

  if (decision.action === "cooldown") {
    if (decision.next) {
      await admin.from("password_reset_attempts").upsert(
        {
          email,
          attempt_count: decision.next.attemptCount,
          block_count: decision.next.blockCount,
          blocked_until: decision.next.blockedUntil,
          window_start: decision.next.windowStart,
        },
        { onConflict: "email" },
      )
    }
    // Silently blocked for the cooldown window — no send, no disclosure.
    return NextResponse.json(GENERIC_OK, { status: 200 })
  }

  // ── Allowed — record the attempt before doing any work ────────────────────
  await admin.from("password_reset_attempts").upsert(
    {
      email,
      attempt_count: decision.next.attemptCount,
      block_count: decision.next.blockCount,
      blocked_until: decision.next.blockedUntil,
      window_start: decision.next.windowStart,
    },
    { onConflict: "email" },
  )

  // Only send if an account actually exists. The result is never disclosed.
  const { data: profile } = await admin
    .from("profiles")
    .select("first_name, full_name")
    .eq("email", email)
    .maybeSingle<{ first_name: string | null; full_name: string }>()

  if (profile) {
    const appUrl =
      process.env.NEXT_PUBLIC_APP_URL ?? "https://metamorfosisllc.com"
    const redirectTo = `${appUrl}/auth/callback?next=/reset-password`

    // Generate the recovery link ourselves and deliver it through Resend, so the
    // email comes from no-reply@metamorfosisllc.com instead of Supabase's
    // default SMTP (which was silently dropping these messages).
    const { data: link, error: linkError } =
      await admin.auth.admin.generateLink({
        type: "recovery",
        email,
        options: { redirectTo },
      })

    if (linkError || !link.properties?.hashed_token) {
      console.error(
        "[forgot-password] generateLink failed:",
        linkError ? JSON.stringify(linkError) : "no hashed_token returned",
        "| response keys:",
        link ? Object.keys(link) : "null",
        "| properties:",
        link?.properties ? Object.keys(link.properties) : "null",
      )
    } else {
      const resetUrl = `${appUrl}/auth/callback?token_hash=${link.properties.hashed_token}&type=recovery&next=/reset-password`

      // Fire-and-forget — a delivery failure is logged but never disclosed to
      // the caller, preserving the generic response.
      try {
        await sendPasswordReset({
          to: email,
          name: profile.first_name ?? profile.full_name.split(" ")[0] ?? "",
          resetUrl,
          expiresInMinutes: RESET_LINK_EXPIRY_MINUTES,
        })
      } catch (err) {
        console.error("[forgot-password] reset email failed:", err)
      }
    }
  }

  return NextResponse.json(GENERIC_OK, { status: 200 })
}
